version: '3'

services:
  micromonitor:
    build: .
    container_name: microservice-monitor
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./config.yaml:/app/config.yaml
    environment:
      - DATABASE_URI=/data/monitor.db
      - IMPORT_CONFIG_FILE=/app/config.yaml
      - FLASK_ENV=production
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped

volumes:
  prometheus_data:
