global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Örnek NodeExporter metrikleri
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Örnek demo mikro servisler
  - job_name: 'demo_microservices'
    static_configs:
      - targets: ['localhost:8081', 'localhost:8082']
        labels:
          group: 'demo'
